name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.3'

    - name: Install dependencies
      run: pip install -r requirements.txt
      
    - name: List files in root and tests directory
      run: |
        ls -R
        ls -R tests

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$(pwd):${PYTHONPATH}" >> $GITHUB_ENV

    - name: Run tests
      run: pytest tests --maxfail=1 --disable-warnings -q